# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # todo
#    serializer:
#        normalization_context:
#            format_key: 'd:m:Y'
#        denormalization_context:
#            format_key: 'd:m:Y'

#    serializer:
#        normalizer:
#            default_context:
#                format_key: 'd:m:Y'
#        denormalizer:
#            default_context:
#                format_key: 'd:m:Y'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
